spring:
  application:
    name: KnCareApp

  datasource:
    url: "jdbc:postgresql://localhost:5432/KNCare"
    username: "postgres"
    password: "stefan0"

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: false
  liquibase:
    enabled: false
#
#  profiles:
#    active: "dev"

server:
  port: 8000

debug: false

#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true

