spring:
  application:
    name: KnCareApp

  datasource:
    url: "jdbc:postgresql://localhost:5432/caredb"
    username: "postgres"
    password: "postgres"

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: false

  liquibase:
    enabled: true
    change-log: "classpath:/liquibase/changelog-master.xml"

#
#  profiles:
#    active: "dev"

server:
  port: 8080

debug: false

logging:
  level:
    liquibase: INFO

#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true

